# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [ --branch, master ]
      - id: trailing-whitespace
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cppcheck
        args: [ -Iinclude/ ]
  - repo: https://github.com/SheyDenis/pre-commit-hooks
    rev: 0.2.4
    hooks:
      - id: clang-format-hook
      - id: dev-marker-hook
      - id: isort-hook
      - id: line-endings-hook
      - id: mypy-hook
      - id: pylint-hook
      - id: symbolic-links-hook
      - id: xenon-hook
      - id: yapf-hook
