# Generated by Django 5.0.6 on 2024-05-25 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_watchlist_watchlist_unique_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
